config/routes.rb
Graph::Application.routes.draw do
  resources :points

  root :to => "points#index"
end

app/models/data_entry.rb
class DataEntry < ActiveRecord::Base
end

app/models/point.rb
class Point < ActiveRecord::Base

  # def as_json(options={})
  # super(:include => :rating)
  # end

  def self.chart_points
    all.map(&:rating)
  end

end

app/models/weight.rb
class Weight < ActiveRecord::Base
  validates :name, :presence => true
  validates :weight,  :presence => true

	# def as_json(options={})
	# super(:include => :weight)
	# end

  def weight_in_kg
  end

  def self.chart_weights
  	all.map(&:weight)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.all
	end
end

app/controllers/data_entries_controller.rb
class DataEntriesController < ApplicationController
  # GET /data_entries
  # GET /data_entries.json
  def index
    @data_entries = DataEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @data_entries }
    end
  end

  # GET /data_entries/1
  # GET /data_entries/1.json
  def show
    @data_entry = DataEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @data_entry }
    end
  end

  # GET /data_entries/new
  # GET /data_entries/new.json
  def new
    @data_entry = DataEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @data_entry }
    end
  end

  # GET /data_entries/1/edit
  def edit
    @data_entry = DataEntry.find(params[:id])
  end

  # POST /data_entries
  # POST /data_entries.json
  def create
    @data_entry = DataEntry.new(params[:data_entry])

    respond_to do |format|
      if @data_entry.save
        format.html { redirect_to @data_entry, notice: 'Data entry was successfully created.' }
        format.json { render json: @data_entry, status: :created, location: @data_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @data_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data_entries/1
  # PUT /data_entries/1.json
  def update
    @data_entry = DataEntry.find(params[:id])

    respond_to do |format|
      if @data_entry.update_attributes(params[:data_entry])
        format.html { redirect_to @data_entry, notice: 'Data entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @data_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_entries/1
  # DELETE /data_entries/1.json
  def destroy
    @data_entry = DataEntry.find(params[:id])
    @data_entry.destroy

    respond_to do |format|
      format.html { redirect_to data_entries_url }
      format.json { head :no_content }
    end
  end

  def filter
    minimum = params[:minimum] || 0
    @data_entries = DataEntry.where(:weight => 100..155)
   

    respond_to do |format|
      format.html # filter.html.erb
      format.json { render json: @data_entries }
    end
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  # GET /points
  # GET /points.json
  def index
    @points = Point.all
    @chart_points = Point.chart_points.collect{|i| i.to_i}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: Point.chart_points }
    end
  end

  # GET /points/1
  # GET /points/1.json
  def show
    @point = Point.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/new
  # GET /points/new.json
  def new
    @point = Point.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(params[:point])

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render json: @point, status: :created, location: @point }
      else
        format.html { render action: "new" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /points/1
  # PUT /points/1.json
  def update
    @point = Point.find(params[:id])

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to points_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  # GET /weights
  # GET /weights.json
  def index
    @weights = Weight.all
    @chart_weights = Weight.chart_weights

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json:  Weight.chart_weights }
    end
  end

  # GET /weights/1
  # GET /weights/1.json
  def show
    @weight = Weight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weight }
    end
  end

  # GET /weights/new
  # GET /weights/new.json
  def new
    @weight = Weight.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weight }
    end
  end

  # GET /weights/1/edit
  def edit
    @weight = Weight.find(params[:id])
  end

  # POST /weights
  # POST /weights.json
  def create
    @weight = Weight.new(params[:weight])

    respond_to do |format|
      if @weight.save
        format.html { redirect_to @weight, notice: 'Weight was successfully created.' }
        format.json { render json: @weight, status: :created, location: @weight }
      else
        format.html { render action: "new" }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weights/1
  # PUT /weights/1.json
  def update
    @weight = Weight.find(params[:id])

    respond_to do |format|
      if @weight.update_attributes(params[:weight])
        format.html { redirect_to @weight, notice: 'Weight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weights/1
  # DELETE /weights/1.json
  def destroy
    @weight = Weight.find(params[:id])
    @weight.destroy

    respond_to do |format|
      format.html { redirect_to weights_url }
      format.json { head :no_content }
    end
  end

  def filter
    minimum = params[:minimum] || 0
    @data_entries = Weight.where(:weight => 100..155)
   

    respond_to do |format|
      format.html # filter.html.erb
      format.json { render json: @weights }
    end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/data_entries_helper.rb
module DataEntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/books/index.html.erb
<h1> Listing Books </h1>

<table>
	<tr>
		<th>Title</th>
		<th>Summary</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

<% @books.each do |book| %>
	<tr>
		<td><%= book.title %></td>
		<td><%= book.content %></td>
		<td><%= link_to 'Show', book %></td>
		<td><%= link_to 'Edit', edit_book_path(book) %></td>
		<td><%= link_to 'Remove', book, :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
<% end %>
</table>

<br />

<%= link_to 'New book', new_book_path %>

app/views/data_entries/_form.html.erb
<%= form_for(@data_entry) do |f| %>
  <% if @data_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_entry.errors.count, "error") %> prohibited this data_entry from being saved:</h2>

      <ul>
      <% @data_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_entries/edit.html.erb
<h1>Editing data_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_entry %> |
<%= link_to 'Back', data_entries_path %>

app/views/data_entries/filter.html.erb
<h1>Filter</h1>

<table>
  <tr>
    <th>Date</th>
  </tr>

<% @data_entries.each do |data_entry| %>
  <tr>
    <td><%= data_entry.weight %></td>
    <td><%= data_entry.created_at %></td>
    <td><%= link_to 'Show', data_entry %></td>
    <td><%= link_to 'Edit', edit_data_entry_path(data_entry) %></td>
    <td><%= link_to 'Destroy', data_entry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Data entry', new_data_entry_path %>

app/views/data_entries/index.html.erb
<h1>Listing Books</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Summary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.content %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Remove', book, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'New book', new_book_path %>

app/views/data_entries/new.html.erb
<h1>New data_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', data_entries_path %>

app/views/data_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Weight:</b>
  <%= @data_entry.weight %>
</p>

<p>



<%= link_to 'Edit', edit_data_entry_path(@data_entry) %> |
<%= link_to 'Back', data_entries_path %>

app/views/home/index.html.erb
<h3>Home</h3>

app/views/layouts/_navigation.html.erb
<%= link_to "Graph", root_path, :class => 'brand' %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Graph" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">



              <% flash.each do |name, msg| %>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                  <a class="close" data-dismiss="alert">×</a>
                  <%= msg %>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Listing points</h1>

<script type="text/javascript" charset="utf-8">
  $(function(){
    
    
    new Highcharts.Chart({
      chart: {
        renderTo: "point_chart"
      },
      title: {
        text: "Weight by Minute"
      },
      xAxis: {
        type: "datetime"
      },
      yAxis: {
        title: {
          text: "pounds"
        }
      },
      series: [{
        pointInterval: <%= 1.day * 1000 %>,
        pointStart: <%= 3.weeks.ago.to_i * 1000 %>,
        data: <%= @chart_points %>
      }]
    });
  });
</script>

<div id="point_chart"></div>

<table>
  <tr>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @points.each do |point| %>
  <tr>
    <td><%= point.rating %></td>
    <td><%= link_to 'Show', point %></td>
    <td><%= link_to 'Edit', edit_point_path(point) %></td>
    <td><%= link_to 'Destroy', point, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Point', new_point_path %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rating:</b>
  <%= @point.rating %>
</p>


<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>

app/views/weights/_form.html.erb
<%= form_for(@weight) do |f| %>
  <% if @weight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weight.errors.count, "error") %> prohibited this weight from being saved:</h2>

      <ul>
      <% @weight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weights/edit.html.erb
<h1>Editing weight</h1>

<%= render 'form' %>

<%= link_to 'Show', @weight %> |
<%= link_to 'Back', weights_path %>

app/views/weights/filter.html.erb
<h1>Filter</h1>

<table>
  <tr>
    <th>Date</th>
  </tr>

<% @data_entries.each do |data_entry| %>
  <tr>
    <td><%= data_entry.weight %></td>
    <td><%= data_entry.created_at %></td>
    <td><%= link_to 'Show', data_entry %></td>
    <td><%= link_to 'Edit', edit_data_entry_path(data_entry) %></td>
    <td><%= link_to 'Destroy', data_entry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Data entry', new_data_entry_path %>

app/views/weights/index.html copy.erb
<h1>Listing Weights</h1>

<script type="text/javascript" charset="utf-8">
	$(function(){
		
		var entries = jQuery.parseJSON(weights.json);
		
		new Highcharts.Chart({
			chart: {
				renderTo: "weight_chart"
			},
			title: {
				text: "Weight by Minute"
			},
			xAxis: {
				type: "datetime"
			},
			yAxis: {
				title: {
					text: "pounds"
				}
			},
			series: [{
				pointInterval: <%= 1.day * 1000 %>,
				pointStart: <%= 3.weeks.ago.to_i * 1000 %>,
				data: parseJSON(entries.weight)
			}]
		});
	});
</script>

<div id="weight_chart" style="width:560px; height:300px; margin: 10px auto;"></div>


<table>
  <tr>
    <th>Name</th>
    <th>Weight</th>
    <th>Time</th>
    <th></th>
    <th></th>
  </tr>

<% @weights.each do |weight| %>
  <tr>
    <td><%= weight.name %></td>
    <td><%= weight.weight %></td>
	<td><%= weight.created_at %></td>
    <td><%= link_to 'Show', weight %></td>
    <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
    <td><%= link_to 'Destroy', weight, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Weight', new_weight_path %>
<%= link_to 'filter', filter_weights_path %>

app/views/weights/index.html.erb
<h1>Listing Weights</h1>

<script type="text/javascript" charset="utf-8">
	$(function(){
		
		
		new Highcharts.Chart({
			chart: {
				renderTo: "weight_chart"
			},
			title: {
				text: "Weight by Minute"
			},
			xAxis: {
				type: "datetime"
			},
			yAxis: {
				title: {
					text: "pounds"
				}
			},
			series: [{
				pointInterval: <%= 1.day * 1000 %>,
				pointStart: <%= 3.weeks.ago.to_i * 1000 %>,
				data: <%= @chart_weights %>
			}]
		});
	});
</script>

<div id="weight_chart" style="width:560px; height:300px; margin: 10px auto;"></div>


<table>
  <tr>
    <th>Name</th>
    <th>Weight</th>
    <th>Time</th>
    <th></th>
    <th></th>
  </tr>

<% @weights.each do |weight| %>
  <tr>
    <td><%= weight.name %></td>
    <td><%= weight.weight %></td>
	<td><%= weight.created_at %></td>
    <td><%= link_to 'Show', weight %></td>
    <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
    <td><%= link_to 'Destroy', weight, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Weight', new_weight_path %>
<%= link_to 'filter', filter_weights_path %>

app/views/weights/new.html.erb
<h1>New weight</h1>

<%= render 'form' %>

<%= link_to 'Back', weights_path %>

app/views/weights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @weight.name %>
</p>

<p>
  <b>Weight:</b>
  <%= @weight.weight %>
</p>


<%= link_to 'Edit', edit_weight_path(@weight) %> |
<%= link_to 'Back', weights_path %>